Kd: !!python/object/apply:array.array
- d
- - 100.0
  - 50.0
Kp: !!python/object/apply:array.array
- d
- - 1500.0
  - 1000.0
Md: !!python/object/apply:array.array
- d
- - 1.0
  - 10.0
start_type_description_service: true
use_sim_time: false
