impedence_control_node:
  ros__parameters:
    use_sim_time: true
    Kp: [15000.0, 15000.0]
    Kd: [100.0, 100.0]
    Md: [1.0, 1.0]

    PID:
      Kp: [100.0, 100.0]
      Ki: [0.001, 0.001]
      Kd: [1.0, 1.0]

    Landing:
      Kp: [10000.0, 1000.0]
      Kd: [200.0, 200.0]
      Md: [5.0, 2.0]


    