<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <xacro:arg name="use_sim_time" default="false" />
    <xacro:arg name="torque_control" default="false" />
    <xacro:arg name="position_control" default="false" />
    <xacro:property name="L1_length" default="0.093732"/>
    <xacro:property name="L2_length" default="0.125"/>
    <xacro:property name="max_torque" default="20.1"/>
    <link name="world">
    </link>

    <joint name="slider_joint" type="prismatic">
        <parent link="world" />
        <child link="base_link" />
        <origin xyz="0 0 1.0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="0" lower="-10" upper="10" velocity="100.0" />
        <dynamics damping="0.0" friction="0.0" />
    </joint>

    <link name="base_link">
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
        </inertial>
    </link>

    <joint name="hip_joint" type="revolute">
        <parent link="base_link" />
        <child link="hip_link" />
        <origin xyz="0 0 0" rpy="${pi/2} ${pi/2} 0" />
        <axis xyz="0 0 1" />
        <limit effort="${max_torque}" lower="-${pi}" upper="${pi}" velocity="62.9" />
        <dynamics damping="0.1" friction="0.1" />
    </joint>

    <link name="hip_link">
        <visual>
            <!-- <origin xyz="${L1_length/2} 0 0" rpy="0 0 0" /> -->
            <geometry>
                <mesh filename="file://$(find robot_description)/meshes/hip.stl"/>
                <!-- for preview -->
                <!-- <mesh filename="../meshes/hip.stl"/> -->
                <!-- <box size="${L1_length} 0.05 0.02" /> -->
            </geometry>
            <material name="blue">
                <color rgba="0 0 1 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="${L1_length/2} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${L1_length} 0.05 0.02" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.6" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
        </inertial>
    </link>

    <joint name="knee_joint" type="revolute">
        <parent link="hip_link" />
        <child link="knee_link" />
        <origin xyz="${L1_length} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="${max_torque}" lower="-${pi}" upper="${pi}" velocity="62.9" />
        <dynamics damping="0.1" friction="0.1" />
    </joint>

    <link name="knee_link">
        <visual>
            <!-- <origin xyz="${L2_length/2} 0 0" rpy="0 0 0" /> -->
            <geometry>
                <mesh filename="file://$(find robot_description)/meshes/tibia.stl"/>
                <!-- for preview -->
                <!-- <mesh filename="../meshes/tibia.stl"/> -->
                <!-- <box size="${L2_length} 0.05 0.02" /> -->
            </geometry>
            <material name="green">
                <color rgba="0 1 0 1" />
            </material>
        </visual>
        <collision>
            <origin xyz="${L2_length/2} 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${L2_length} 0.01 0.04" />
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <mass value="0.1" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
        </inertial>
    </link>

    <!-- This has to be a revolute joint for some dumb reason -->
    <!-- Can also change this manually in the sdf to a fixed joint -->
    <joint name="contact_joint" type="fixed">
    <!-- <joint name="contact_joint" type="revolute"> -->
        <parent link="knee_link" />
        <child link="foot_link" />
        <origin xyz="${L2_length} 0 0" rpy="0 0 0" />
        <axis xyz="0 0 1" />
        <limit effort="1e-5" lower="0" upper="0" velocity="1e-5" />
        <dynamics damping="0.0" friction="0.0" />
    </joint>

    <link name="foot_link">
        <visual>
            <geometry>
                <sphere radius="0.01" />
            </geometry>
        </visual>
        <!-- Something is wrong with the urdf/xacro/sdf conversion.
         This collision name changes when the sim is launched. -->
        <!-- <collision name="foot_collision"> -->
        <collision>
            <geometry>
                <sphere radius="0.01" />
            </geometry>
        </collision>
        <inertial>
            <mass value="0.01" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01" />
        </inertial>
    </link>

    <xacro:if value="$(arg use_sim_time)">
        <xacro:include filename="$(find robot_description)/description/simulation.xacro" />
        <xacro:if value="$(arg torque_control)">
            <xacro:include filename="$(find robot_description)/description/torque_control.xacro" />
        </xacro:if>
        <xacro:if value="$(arg position_control)">
            <xacro:include filename="$(find robot_description)/description/position_control.xacro" />
        </xacro:if>
    </xacro:if>
</robot>